### ISSUE TITLE
FF3 support regression

### ISSUE THREAD

**Issue by Kivutar** [libretro/libretro-ppsspp#78]
I get that segfault when trying to run FF3.

It's a regression.

[New Thread 0x7fffdb93b700 (LWP 18509)]
I: gl_state.cpp:137: I: GPU Vendor : Intel Open Source Technology Center ; renderer: Mesa DRI Intel(R) Ivybridge Mobile  version str: 3.0 Mesa 12.0.1 ; GLSL version str: 1.30
I: gpu_features.cpp:20: I: Checking for GL driver bugs... vendor=0 model='Mesa DRI Intel(R) Ivybridge Mobile '
I: zip_read.cpp:337: I: Not a VFS path: /home/kivutar/Jeux/system/PPSSPP/shaders/defaultshaders.ini . Reading local file.
I: zip_read.cpp:370: I: Not a VFS path: /home/kivutar/Jeux/roms/psp/PSP/shaders . Reading local directory.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Thread 1 "retroarch" received signal SIGABRT, Aborted.
0x00007fffefa2a295 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007fffefa2a295 in raise () from /usr/lib/libc.so.6
#1  0x00007fffefa2b6da in abort () from /usr/lib/libc.so.6
#2  0x00007ffff45e13dd in __gnu_cxx::__verbose_terminate_handler () at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff45df196 in __cxxabiv1::__terminate (handler=<optimized out>) at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007ffff45df1e1 in std::terminate () at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007ffff45df3f8 in __cxxabiv1::__cxa_throw (obj=0x7fffb8000940, tinfo=0x7ffff48c8770 <typeinfo for std::bad_alloc>, dest=0x7ffff45dd540 <std::bad_alloc::~bad_alloc()>)
    at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:87
#6  0x00007ffff45df9ac in operator new (sz=18446744069677240500) at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/new_op.cc:54
#7  0x00007fffe03014c2 in PGF::ReadPtr(unsigned char const*, unsigned long) () from /home/kivutar/.config/retroarch/cores/ppsspp_libretro.so
#8  0x00007fffe032e1ae in __LoadInternalFonts() () from /home/kivutar/.config/retroarch/cores/ppsspp_libretro.so
#9  0x00007fffe032f763 in void WrapU_UU<&(sceFontNewLib(unsigned int, unsigned int))>() () from /home/kivutar/.config/retroarch/cores/ppsspp_libretro.so
#10 0x00007fffe0306b8a in CallSyscallWithFlags(HLEFunction const*) () from /home/kivutar/.config/retroarch/cores/ppsspp_libretro.so
#11 0x00007fffbfc42629 in ?? ()
#12 0x00007fffffffe6fc in ?? ()
#13 0x00007fffffffe6fc in ?? ()
#14 0x0000000000000000 in ?? ()

**Comment by Kivutar** [comment]
It was a font issue on my side
